version: 0.1
tools:
  definitions:
    - name: php-cs-fixer
      runtime: php
      package: friendsofphp/php-cs-fixer
      known_good_version: 3.54.0
      shims: [php-cs-fixer]
      environment:
        - name: PATH
          list: ["${tool}/vendor/bin"]
